Review previous project
AJ193/Review-previous-project pull request #1
Opened 2023-01-22 11:09 UTC by AJ193

add a html file

2023-01-22 11:36 UTC, AJ193 reviewed
### Highlights 👍 

- Get hub repo set up correctly
- good work flow

### Required Changes ♻️ 
- Please see the required changes in the comment below

2023-01-22 11:36 UTC, AJ193 commented on index.html
> +</body>
- Kindly add a more semantic tags to your HTML document to clearly describe 
-  the meaning of each tag both to the developer and the browser.

- Kindly add a css file to style your html.

2023-01-23 07:41 UTC, IngDavidTM requested changes
## Hi @AJ193   🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request uses "Review changes" ✅

## Suggested changes

- [ ] You did an amazing job reviewing the code :+1:, but as a requirement, your comments should be clear and easy to understand. For Example:
  - This is a clear comment: *The README's "Built With" and "Getting Started" sections are currently empty. Why don't you add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional?*
  - This is a vague comment: *The README is not descriptive, why don't you make it better?*

- [x] I think it would be better if your comments always include an explanation to help the student understand what you mean in every comment :+1:. You can check more about it [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-communicate)

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 09:37 UTC, AJ193 reviewed
### Highlights 👍 
- Good github workflow

### Required changes ♻️ 
- Checkout the comments for more information.
- Kindly add a README file to your project to make it look more professional and this makes it easier for other people to understand your project and objectives. Check out this [template](https://github.com/microverseinc/readme-template).

2023-01-23 09:37 UTC, AJ193 commented on index.html
> +</head>
- Kindly add a css file to style your index.html file which will enable you to add styling to your markup.
- Also remember to link it in the ```<head>``` section of your index.html. 
example:
```<link rel="stylesheet" href="styles.css">```

2023-01-23 09:50 UTC, Olamarx approved these changes
Hi @AJ193,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>
## Highlights
- Polite comments ✔️ 
- Reasons for changes ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 09:52 UTC, merged